/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.modelBacSiCaLam;
import model.modelBangCaLamViec;
import repository.CaLamViecRepository;

/**
 *
 * @author Admin
 */
public class caLamViec extends javax.swing.JPanel {

    private CaLamViecRepository rp1= new CaLamViecRepository();
    private DefaultTableModel mol= new DefaultTableModel();
    private int i=-1;
    public caLamViec() {
        initComponents();
        this.fillTable(rp1.getAllBangCaLamViec());
        txt_MaBacSi.setEditable(false);
    }

    void fillTable1(ArrayList<modelBacSiCaLam> list){
         mol=(DefaultTableModel)tbl_BacSi.getModel();
         mol.setRowCount(0);
         for (modelBacSiCaLam x : list) {
             mol.addRow(x.toDataRow());
         }
     }
    
    void fillTable(ArrayList<modelBangCaLamViec> list){
         mol=(DefaultTableModel)tbl_CaLam.getModel();
         mol.setRowCount(0);
         for (modelBangCaLamViec x : list) {
             mol.addRow(x.toDataRow());
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaCaLam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_MaBacSi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_NgayLam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdo_CaSang = new javax.swing.JRadioButton();
        rdo_CaChieu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_GhiChu = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        rdo_DaCoLich = new javax.swing.JRadioButton();
        rdo_ChuaCoLich = new javax.swing.JRadioButton();
        btn_Them = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_BacSi = new javax.swing.JTable();
        txt_ChuyenKhoa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_TimKiem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_CaLam = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1477, 710));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Thiết Lập Ca Làm Việc");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Mã Ca Làm Việc");

        txt_MaCaLam.setEnabled(false);
        txt_MaCaLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaCaLamActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã Bác Sĩ");

        jLabel4.setText("Ngày Làm");

        jLabel5.setText("Ca Làm");

        rdo_CaSang.setText("Ca Sáng");

        rdo_CaChieu.setText("Ca Chiều");

        jLabel6.setText("Ghi chú");

        txt_GhiChu.setColumns(20);
        txt_GhiChu.setRows(5);
        jScrollPane1.setViewportView(txt_GhiChu);

        jLabel7.setText("Trạng thái");

        buttonGroup2.add(rdo_DaCoLich);
        rdo_DaCoLich.setText("Đã Có Lịch");

        buttonGroup2.add(rdo_ChuaCoLich);
        rdo_ChuaCoLich.setText("Chưa Có Lịch");

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_MaBacSi, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                .addComponent(txt_MaCaLam))
                            .addComponent(txt_NgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdo_CaSang)
                                .addGap(69, 69, 69)
                                .addComponent(rdo_CaChieu))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdo_DaCoLich)
                                .addGap(65, 65, 65)
                                .addComponent(rdo_ChuaCoLich))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_Them)
                        .addGap(82, 82, 82)
                        .addComponent(btn_Clear)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MaCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_NgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_MaBacSi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdo_CaSang)
                    .addComponent(rdo_CaChieu))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1)
                        .addGap(187, 187, 187))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(168, 168, 168)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rdo_DaCoLich)
                            .addComponent(rdo_ChuaCoLich))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them)
                            .addComponent(btn_Clear))
                        .addGap(62, 62, 62))))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("BÁC SĨ");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        tbl_BacSi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Bác Sĩ", "Tên ", "Số Điện Thoại", "Chuyên Khoa", "Số Năm Kinh Nghiệm"
            }
        ));
        tbl_BacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BacSiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_BacSi);

        jLabel9.setText("Chuyên Khoa");

        btn_TimKiem.setText("TÌM KIẾM");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(44, 44, 44)
                        .addComponent(txt_ChuyenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_TimKiem)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_ChuyenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("THÔNG TIN CA LÀM VIỆC");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));

        tbl_CaLam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Ca Làm Việc", "Mã Bác Sĩ", "Ngày Làm", "Ca Làm", "Ghi Chú", "Trạng Thái"
            }
        ));
        jScrollPane3.setViewportView(tbl_CaLam);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        String chuyenNgang=txt_ChuyenKhoa.getText().toString();
        this.fillTable1(rp1.getAllBacSiCaLam(chuyenNgang));
        
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void tbl_BacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BacSiMouseClicked
        // TODO add your handling code here:
        i=tbl_BacSi.getSelectedRow();
        txt_MaBacSi.setText(tbl_BacSi.getValueAt(i, 0).toString());
    }//GEN-LAST:event_tbl_BacSiMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        if(this.readForm()!= null){
            
           if(rp1.them(this.readForm())>0){
               //thêm được
               JOptionPane.showMessageDialog(this, "thêm thành công");
               this.fillTable(rp1.getAllBangCaLamViec());
           }
           else //không thêm được
           {
               JOptionPane.showMessageDialog(this, "thêm thất bại");
           }
       }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
        txt_MaCaLam.setText("");
        txt_MaBacSi.setText("");
        txt_GhiChu.setText("");
        
        txt_NgayLam.setText("");
        txt_GhiChu.setText("");
        
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void txt_MaCaLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaCaLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaCaLamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdo_CaChieu;
    private javax.swing.JRadioButton rdo_CaSang;
    private javax.swing.JRadioButton rdo_ChuaCoLich;
    private javax.swing.JRadioButton rdo_DaCoLich;
    private javax.swing.JTable tbl_BacSi;
    private javax.swing.JTable tbl_CaLam;
    private javax.swing.JTextField txt_ChuyenKhoa;
    private javax.swing.JTextArea txt_GhiChu;
    private javax.swing.JTextField txt_MaBacSi;
    private javax.swing.JTextField txt_MaCaLam;
    private javax.swing.JTextField txt_NgayLam;
    // End of variables declaration//GEN-END:variables

    modelBangCaLamViec readForm(){
        
        
        String maCaLam;
        UUID uuid = UUID.randomUUID();
        maCaLam="LH"+uuid.toString().substring(0, 6);
        
        String maBacSi;
        String ngayLam;
        int caLam;
        String ghiChu;
        int trangThai;
        
        maBacSi=txt_MaBacSi.getText().trim();
        ngayLam=txt_NgayLam.getText().trim();
        String ngayCheck= "\\d{4}-\\d{2}-\\d{2}";
        if(ngayLam.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ngày làm không được để trống");
            txt_NgayLam.requestFocus();
            return null;
        }else if(!ngayLam.matches(ngayCheck)){
            JOptionPane.showMessageDialog(this, "Ngày sai định dạng");
            txt_NgayLam.requestFocus();
            return null;
        }
        
            
        
        if(ngayLam.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ngày làm không được để trống");
            txt_NgayLam.requestFocus();
            return null;
        }else{
            if(ngayLam.matches(ngayCheck)){
                
            }
        };
        if(ngayLam.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ngày làm không được để trống");
            txt_NgayLam.requestFocus();
            return null;
        }else{
            if(ngayLam.matches(ngayCheck)){
                
            }
        }
        
        if(rdo_CaSang.isSelected())
            caLam=0;
        else caLam=1;
        
        ghiChu=txt_GhiChu.getText().trim();
        if(ghiChu.isEmpty()){
            JOptionPane.showMessageDialog(this, "Ghi chú không được để trống");
            txt_GhiChu.requestFocus();
            return null;
        }
        
        if(rdo_ChuaCoLich.isSelected())
            trangThai=0;
        else trangThai=1;
        
        return new modelBangCaLamViec(maCaLam,maBacSi, ngayLam, true, ghiChu, true);
    }
}
